markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: lity-lee
author: "李同垒"
email: lity_lee#163.com
name: "李同垒的博客"
url: http://www.lity-lee.org
domain: www.lity-lee.org
all_categories: [
["android", "Android","/posts/android.html"], 
["program", "Program","/posts/program.html"],
["web", "Web","/posts/web.html"], 
["linux", "Linux","/posts/linux.html"],
["cygwin", "Cygwin","/posts/cygwin.html"], 
["mlai", "Mlai","/posts/mlai.html"],
["about", "About","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
